### ISSUE TITLE
Add a linter file

### ISSUE THREAD

**Issue by jGleitz** [HelfenKannJeder/come2help-web#12]
We should set up (a) configuration file(s) for [JSLint](http://www.jslint.com/) and / or [ESLint](http://eslint.org/). Complying with them should be mandatory for Pull Requests to be accepted.

**Comment by vzickner** [comment]
:+1:

**Comment by jGleitz** [comment]
While we're on it, we could also at a config file for [JS Beautifier](http://jsbeautifier.org/) which I think helps a lot – especially if someone's normally using another code style than the one we'll pick.

**Comment by jGleitz** [comment]
After reading [this comparison](http://www.sitepoint.com/comparison-javascript-linting-tools/) I think ESLint is enough.
