### ISSUE TITLE
Disable browser caching in development web server

### ISSUE THREAD

**Issue by jGleitz** [HelfenKannJeder/come2help-web#18]
The python web server delivers its resources with the `Expires` HTTP header set.

This is unfortunate for development, as resources change and one might forget to disable caching.

**Comment by BassT** [comment]
When the developer console is opened, you can disable caching [easily](http://stackoverflow.com/questions/5690269/disabling-chrome-cache-for-website-development). Or are you talking about some other situation I'm not getting?

**Comment by vzickner** [comment]
He is talking about the python standalone webserver:
`python3 -m http.server`
But yes, it is also possible to disable caching in the browser.

**Comment by jGleitz** [comment]
I know it's easy to disable caching through the developer tools (that's my default, actually), but I forgot about caching when I was looking at the site from my non-development browser and tried to fix a bug that did not exist any more.
So I thought others might fall into that trap sometime, so disabling browser caching in the webserver at the first place might be good. (It does not make sense that he sets an expiry date anyway).

**Comment by pzzz** [comment]
+1

**Comment by jGleitz** [comment]
Fixed with #27
