### ISSUE TITLE
Add overview of registered users

### ISSUE THREAD

**Issue by vzickner** [HelfenKannJeder/come2help-web#21]
Allow Filters:
- Location
- Distance
- Age
- ....

**Comment by jGleitz** [comment]
> Allow Filters

Sorry, I don't quite get that. Why would I want to filter my profile?

**Comment by vzickner** [comment]
This overview is for people from organisations. They want to search/filter users/volunteers.

**Comment by BassT** [comment]
Search result table example design from Unify Bootstrap template:
http://htmlstream.com/preview/unify-v1.8/page_search_table.html

**Comment by vzickner** [comment]
According to [this stackoverflow post](http://stackoverflow.com/questions/21375073/best-way-to-represent-a-grid-or-table-in-angularjs-with-bootstrap-3) we should use [Smart Table](http://lorenzofox3.github.io/smart-table-website/) for rendering tables. Maybe we should define, which part of the content filtering is done by the frontend and which is done by the backend.
