### ISSUE TITLE
Setup Test Environment

### ISSUE THREAD

**Issue by vzickner** [HelfenKannJeder/come2help-web#3]

**Comment by jGleitz** [comment]
I propose to write a message to the guys at [Browserstack](https://www.browserstack.com/). They say they give away their service to open source projects for free, and I think we fit that. 
Browserstack would give us automated testing in real browsers, integrated into anything I know: [Browserstack Automate](https://www.browserstack.com/automate)

**Comment by vzickner** [comment]
Message to BrowserStack is sent.
