### ISSUE TITLE
Define target browsers

### ISSUE THREAD

**Issue by jGleitz** [HelfenKannJeder/come2help-web#30]
Browser compatibility is (unfortunately) still a serious issue. For example, our momentary example site does _not_ run in IE 9 (see below). 

Therefore, we should make up a well defined set of browsers to run our tests against. 
Such a set could be defined like 

> Assert that our site runs well in all browsers matching the [browserslist](https://github.com/ai/browserslist) query `X` at any time. 

For example, at the point of writing, [`browserslist`](https://github.com/ai/browserslist)`"> 0.8% in DE"` evaluates to:

```
and_chr 0
android 4.4
android 4.4.3-4.4.4
android 4.2-4.3
chrome 45
chrome 44
edge 12
firefox 41
firefox 40
firefox 39
firefox 38
ie 11
ie 10
ie 9
ios_saf 9
ios_saf 8.1-8.4
opera 31
safari 8
```

I'd like to hear your thoughts about this.

Example site in IE 9 / Windows 7 on browserstack: 

![IE 9
![IE 9 on Windows 7](https://cloud.githubusercontent.com/assets/4305652/10827917/c9b24b3e-7e71-11e5-9339-de00b9d7e8a7.jpg)
 on Windows 7](https://cloud.githubusercontent.com/assets/4305652/10827823/377d6bcc-7e71-11e5-9c9a-3d844f256802.jpg)

**Comment by jGleitz** [comment]
`browserslist ">1% in DE"`:

```
and_chr 0
android 4.4
android 4.2-4.3
chrome 45
chrome 44
edge 12
firefox 41
firefox 40
firefox 39
firefox 38
ie 11
ios_saf 9
ios_saf 8.1-8.4
safari 8
```

**Comment by vzickner** [comment]
For the first step ignore old browsers like IE 9. This can be fixed later.

**Comment by pzzz** [comment]
Totally agree on that.

Further I think its always worth thinking about whether to support Browsers after EOL at all or whether to provide the users of those browsers some Update informations / help, as they are potential Security issues for the users themselves...

**Comment by pzzz** [comment]
In addition we could try to get some data from our users in the first phase and learn which browsers they use, and then refine our target browser list based on that insights...

**Comment by vzickner** [comment]
Additionally we can add a security warning, if they use an unsupported browser.

**Comment by pzzz** [comment]
Thats a good idea...

Now I also found the plugin I had in my mind when speaking about upgrade notices:
https://github.com/burocratik/outdated-browser

**Comment by jGleitz** [comment]
+1 for a warning in outdated browsers.

**Comment by jGleitz** [comment]
target browsers are implicitly defined in `test/behaviour/protractor.browserstack.conf`. I thus consider this issue as closed.

I will open a new issue for a warning for outdated browsers.

For any comments on the selected target browsers, please open a new issue.
