### ISSUE TITLE
Switch CSS to SASS

### ISSUE THREAD

**Issue by vzickner** [HelfenKannJeder/come2help-web#5]
Something like http://lesscss.org/ should be used, instead of plain CSS.

**Comment by BassT** [comment]
:+1:

**Comment by jGleitz** [comment]
I'd prefer SCSS for that matter

**Comment by vzickner** [comment]
What are the benefits of SCSS?

**Comment by jGleitz** [comment]
Some are described in [It's time to switch to SASS](http://www.zingdesign.com/less-vs-sass-its-time-to-switch-to-sass/). General speaking, I found their way of doing things (functions, mixins, control flow control, `$`-variables) more intuitive to write. I found myself looking up less when writing SCSS, compared to LESS. But that's personal, of course.

**Comment by BassT** [comment]
I also heard SASS being superior to LESS.

**Comment by jGleitz** [comment]
Implemented in #29
