### ISSUE TITLE
Switch Javascript to a typesafe language

### ISSUE THREAD

**Issue by vzickner** [HelfenKannJeder/come2help-web#6]
A typesafe language should be used, instead of plain Javascript.

For example:
- <a href="https://www.npmjs.com/package/compiled-coffee">Compiled Coffee</a>
- <a href="http://www.typescriptlang.org/">Typescript</a>

**Comment by BassT** [comment]
I don't think typesafety is a big issue when using [JSLint](http://www.jslint.com/help.html) while coding and I'm not sure if the there's overhead if using a language that compiles to JS.

**Comment by vzickner** [comment]
Can we automate this with travis ci? :-)

**Comment by jGleitz** [comment]
From my point of view, having a type safe language is a big plus. We will most definite need a build tool, so there is no overhead at all, as compilation into JavaScript will be done in the build step, together with further optimizations.

**Comment by BassT** [comment]
I'm also fine with a typesafe language, as long as it doesn't take to long setting it up. Do it. But more important is getting a prototype done.

**Comment by vzickner** [comment]
Maybe <a href="http://eslint.org/">ESLint</a> is enough for us?

**Comment by jGleitz** [comment]
I'd propose these to options:
- If we only want to add type information but write plain JavaScript, I'd use [Google Closure Type Annotations](https://developers.google.com/closure/compiler/docs/js-for-compiler). These are like JSDoc, but can be checked by the Closure Compiler. It uses the type information to further minify when compiling, which is cool, too.
- If we are willing to write another language, I'd use [Dart](https://www.dartlang.org/). Dart does not try to be compatible or similar to JavaScript and therefore takes away all the JavaScript-ugliness. It has a powerful, yet very intuitive (to me) syntax and style.
  There is [an official implementation of Angular in Dart](https://angulardart.org/) that uses Dart's features. The implementation is by the Google Team itself and may be [considered equal, if not better, than the JS implementation](http://stackoverflow.com/questions/19993377/differences-between-angular-js-and-angular-dart).

Adopting either of the options will require very little effort as we are already using a build system.

**Comment by BassT** [comment]
+1 Google Closure Type Annotations

**Comment by jGleitz** [comment]
Practically any work is being held back by this decision. Given the low interaction on this issue, I don't assume people are too controversial about it. 
Let's set ourselves a deadline, like today, 3pm. As Closure Type Annotations got the most +1s, (2), we could probably use them.

**Comment by vzickner** [comment]
Deadline today 3pm is fine.
+1 Google Closure Type Annotations

**Comment by SrTobi** [comment]
+1 Dart :)

**Comment by jGleitz** [comment]
> Deadline today 3pm is fine.

I think we can close this.

**Comment by BassT** [comment]
Google Closure Type Annotations has been added to the project. I'm closing this.
