### ISSUE TITLE
Add build environment

### ISSUE THREAD

**Issue by vzickner** [HelfenKannJeder/come2help-web#7]
Add a automatic build environment, which is useful in combination with #5 and #6.

**Comment by vzickner** [comment]
This can be done by using npm

**Comment by jGleitz** [comment]
We're now using bower _and_ npm for dependency management. Is there a good reason for it?

**Comment by vzickner** [comment]
The reason is to separate frontend dependencies (bower) from development dependencies (npm). But until now the separation is missing ;-)

**Comment by jGleitz** [comment]
Oh, okay.
